In [1]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt
%matplotlib inline

In [94]:
df_test = pd.read_csv('test.csv')

In [95]:
df_train = df_test[['Pclass','Sex','Age','SibSp','Parch','Fare','Cabin','Embarked']]

In [96]:
df_train['Age'] = df_train['Age'].fillna(df_train['Age'].mean())
df_train['Fare'] = df_train['Fare'].fillna(df_train['Fare'].mean())
df_train['Cabin'] = df_train['Cabin'].fillna(-1)
df_train['Embarked'] = df_train['Embarked'].fillna(-1)

/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [97]:
for field in ['Sex','Embarked']:
    df_dummy = pd.get_dummies(df_train[field],prefix = field)
    df_train = pd.concat([df_train,df_dummy],axis  = 1)
    df_train = df_train.drop(field,axis = 1)

In [98]:
df_train = df_train.drop('Cabin', axis = 1)

In [99]:
cols = df_train.columns.tolist()
cols.insert(7,'Embarked_-1')
df_train_p = pd.DataFrame(df_train,columns=cols)
df_train_p['Embarked_-1'] = df_train_p['Embarked_-1'].fillna(0)

In [109]:
df_train_p

,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_-1,Embarked_C,Embarked_Q,Embarked_S
0,3,34.50000,0,0,7.8292,0,1,0.0,0,1,0
1,3,47.00000,1,0,7.0000,1,0,0.0,0,0,1
2,2,62.00000,0,0,9.6875,0,1,0.0,0,1,0
3,3,27.00000,0,0,8.6625,0,1,0.0,0,0,1
4,3,22.00000,1,1,12.2875,1,0,0.0,0,0,1
5,3,14.00000,0,0,9.2250,0,1,0.0,0,0,1
6,3,30.00000,0,0,7.6292,1,0,0.0,0,1,0
7,2,26.00000,1,1,29.0000,0,1,0.0,0,0,1
8,3,18.00000,0,0,7.2292,1,0,0.0,1,0,0
9,3,21.00000,2,0,24.1500,0,1,0.0,0,0,1
10,3,30.27259,0,0,7.8958,0,1,0.0,0,0,1
11,1,46.00000,0,0,26.0000,0,1,0.0,0,0,1
12,1,23.00000,1,0,82.2667,1,0,0.0,0,0,1
13,2,63.00000,1,0,26.0000,0,1,0.0,0,0,1
14,1,47.00000,1,0,61.1750,1,0,0.0,0,0,1
15,2,24.00000,1,0,27.7208,1,0,0.0,1,0,0
16,2,35.00000,0,0,12.3500,0,1,0.0,0,1,0
17,3,21.00000,0,0,7.2250,0,1,0.0,1,0,0
18,3,27.00000,1,0,7.9250,1,0,0.0,0,0,1
19,3,45.00000,0,0,7.2250,1,0,0.0,1,0,0
20,1,55.00000,1,0,59.4000,0,1,0.0,1,0,0
21,3,9.00000,0,1,3.1708,0,1,0.0,0,0,1
22,1,30.27259,0,0,31.6833,1,0,0.0,0,0,1
23,1,21.00000,0,1,61.3792,0,1,0.0,1,0,0
24,1,48.00000,1,3,262.3750,1,0,0.0,1,0,0
25,3,50.00000,1,0,14.5000,0,1,0.0,0,0,1
26,1,22.00000,0,1,61.9792,1,0,0.0,1,0,0
27,3,22.50000,0,0,7.2250,0,1,0.0,1,0,0
28,1,41.00000,0,0,30.5000,0,1,0.0,0,0,1
29,3,30.27259,2,0,21.6792,0,1,0.0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
388,3,21.00000,0,0,7.7500,0,1,0.0,0,1,0
389,3,6.00000,3,1,21.0750,0,1,0.0,0,0,1
390,1,23.00000,0,0,93.5000,0,1,0.0,0,0,1
391,1,51.00000,0,1,39.4000,1,0,0.0,0,0,1
392,3,13.00000,0,2,20.2500,0,1,0.0,0,0,1
393,2,47.00000,0,0,10.5000,0,1,0.0,0,0,1
394,3,29.00000,3,1,22.0250,0,1,0.0,0,0,1
395,1,18.00000,1,0,60.0000,1,0,0.0,0,0,1
396,3,24.00000,0,0,7.2500,0,1,0.0,0,1,0
397,1,48.00000,1,1,79.2000,1,0,0.0,1,0,0
398,3,22.00000,0,0,7.7750,0,1,0.0,0,0,1
399,3,31.00000,0,0,7.7333,0,1,0.0,0,1,0
400,1,30.00000,0,0,164.8667,1,0,0.0,0,0,1
401,2,38.00000,1,0,21.0000,0,1,0.0,0,0,1
402,1,22.00000,0,1,59.4000,1,0,0.0,1,0,0
403,1,17.00000,0,0,47.1000,0,1,0.0,0,0,1
404,1,43.00000,1,0,27.7208,0,1,0.0,1,0,0
405,2,20.00000,0,0,13.8625,0,1,0.0,1,0,0
406,2,23.00000,1,0,10.5000,0,1,0.0,0,0,1
407,1,50.00000,1,1,211.5000,0,1,0.0,1,0,0
408,3,30.27259,0,0,7.7208,1,0,0.0,0,1,0
409,3,3.00000,1,1,13.7750,1,0,0.0,0,0,1
410,3,30.27259,0,0,7.7500,1,0,0.0,0,1,0
411,1,37.00000,1,0,90.0000,1,0,0.0,0,1,0
412,3,28.00000,0,0,7.7750,1,0,0.0,0,0,1
413,3,30.27259,0,0,8.0500,0,1,0.0,0,0,1
414,1,39.00000,0,0,108.9000,1,0,0.0,1,0,0
415,3,38.50000,0,0,7.2500,0,1,0.0,0,0,1
416,3,30.27259,0,0,8.0500,0,1,0.0,0,0,1
417,3,30.27259,1,1,22.3583,0,1,0.0,1,0,0

In [100]:
x_np = df_train_p.as_matrix().astype(np.float32)

In [101]:
from sklearn.model_selection import train_test_split
import chainer
from chainer import training, Chain
from chainer.training import extensions
from chainer import links as L
from chainer import functions as F
from chainer.datasets import TupleDataset
from chainer import serializers

In [102]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [136]:
class MyChain4(Chain):
    def __init__(self):
        super(MyChain4,self).__init__(
            l1 = L.Linear(None, 100),
            l2 = L.Linear(None, 100),
            l3 = L.Linear(None,100),
            l4 = L.Linear(None,2),
            bn1 = L.BatchNormalization(size = 100),
            bn2 = L.BatchNormalization(size = 100),
            bn3 = L.BatchNormalization(size = 100)
        )
        
    def __call__(self, x):
        h = F.dropout(x,ratio = 0.2)
        h = F.dropout(F.relu(self.bn1(self.l1(x))))
        h = F.dropout(F.relu(self.bn2(self.l2(h))))
        h = F.dropout(F.relu(self.bn3(self.l3(h))))
        y = self.l4(h)
        
        return y

In [131]:
class MyChain(Chain):
    def __init__(self):
        super(MyChain,self).__init__(
            l1 = L.Linear(None, 1000),
            l2 = L.Linear(None,100),
            l3 = L.Linear(None,2),
            bn1 = L.BatchNormalization(size = 1000)
        )
        
    def __call__(self, x):
        h = F.relu(self.bn1(self.l1(x)))
        h = F.dropout(F.relu(self.l2(h)))
        y = self.l3(h)
        
        return y

In [142]:
class MyChain5(Chain):
    def __init__(self):
        super(MyChain5,self).__init__(
            l1 = L.Linear(None, 100),
            l2 = L.Linear(None, 100),
            l3 = L.Linear(None,100),
            l4 = L.Linear(None,2),
            bn1 = L.BatchNormalization(size = 100),
            bn2 = L.BatchNormalization(size = 100),
            bn3 = L.BatchNormalization(size = 100)
        )
        
    def __call__(self, x):
        h = F.dropout(x,ratio = 0.2)
        h = F.dropout(F.relu(self.bn1(self.l1(x))))
        h = F.dropout(F.relu(self.bn2(self.l2(h))))
        h = F.dropout(F.relu(self.bn3(self.l3(h))))
        y = self.l4(h)
        
        return y

In [143]:
model = L.Classifier(MyChain4())
serializers.load_npz('model/model_5.npz',model)

In [144]:
pred = np.argmax(F.softmax(model.predictor(x_np)).data,axis = 1)

In [145]:
df_out =pd.DataFrame(pred, columns=['Survived'])

In [146]:
df_out = pd.concat([df_test[['PassengerId']],df_out],axis=1)

In [147]:
df_out.to_csv('submit/model_5.csv',index=False)