In [23]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
import chainer
from chainer import training, Chain
from chainer.training import extensions
from chainer import links as L
from chainer import functions as F
from chainer.datasets import TupleDataset
from chainer import serializers

from chainer.functions.loss.mean_squared_error import mean_squared_error

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression

In [24]:
df_dev = pd.read_csv('test.csv')

In [43]:
df_test = df_dev[['Pclass','Name','Sex','Age','SibSp','Parch','Fare','Embarked']]

In [44]:
for field in ['Sex','Embarked']:
    df_dummy = pd.get_dummies(df_test[field],prefix = field)
    df_test = pd.concat([df_test,df_dummy],axis  = 1)
    df_test = df_test.drop(field,axis = 1)

In [45]:
def name_classifier(name_df):    
    name_class_df = pd.DataFrame(columns={'miss','mrs','master','mr'})
    
    for name in name_df:        
        if 'Miss' in name:
            df = pd.DataFrame([[1,0,0,0]],columns={'miss','mrs','master','mr'})
        elif 'Mrs' in name:
            df = pd.DataFrame([[0,1,0,0]],columns={'miss','mrs','master','mr'})
        elif 'Master' in name:
            df = pd.DataFrame([[0,0,1,0]],columns={'miss','mrs','master','mr'})
        elif 'Mr' in name:
            df = pd.DataFrame([[0,0,0,1]],columns={'miss','mrs','master','mr'})
        else :
            df = pd.DataFrame([[0,0,0,0]],columns={'miss','mrs','master','mr'})
        name_class_df = name_class_df.append(df,ignore_index=True)        
    return name_class_df

In [46]:
df_name = df_test['Name']
df_name_class = name_classifier(df_name)

In [47]:
df_test = pd.concat([df_test,df_name_class],axis =1)
df_test = df_test.drop('Name',axis = 1)
df_test['Age'] = df_test['Age'].fillna(df_test['Age'].mean())
df_test['Fare'] = df_test['Fare'].fillna(df_test['Fare'].mean())

In [49]:
df_test.to_pickle('test.pkl')

In [48]:
df_test.isnull().sum()

Pclass        0
Age           0
SibSp         0
Parch         0
Fare          0
Sex_female    0
Sex_male      0
Embarked_C    0
Embarked_Q    0
Embarked_S    0
miss          0
mrs           0
master        0
mr            0
dtype: int64

In [50]:
X = df_test.as_matrix().astype(np.float32)

In [31]:
class MyChain(Chain):
    def __init__(self):
        super(MyChain,self).__init__(
            l1 = L.Linear(None, 10),
            l2 = L.Linear(None, 6),
            l3 = L.Linear(None,2),
            bn1 = L.BatchNormalization(size = 14),
            bn2 = L.BatchNormalization(size = 10),
            bn3 = L.BatchNormalization(size = 6)
        )
        
    def __call__(self, x, train = True):
        h = F.dropout(self.bn1(x),ratio = 0.2, train=train)
        h = F.dropout(F.relu(self.bn2(self.l1(x))), train = train)
        h = F.dropout(F.relu(self.bn3(self.l2(h))), train = train)
        y = self.l3(h)
        
        return y

In [60]:
df_pred = pd.DataFrame(index=df_test.index, columns=[])

In [64]:
n_fold = 10

In [66]:
for i in range(n_fold):
    model = L.Classifier(MyChain())
    serializers.load_npz('model/model_'+str(i)+'.npz',model)
    pred = F.softmax(model.predictor(X,train=False)).data[:,1]
    df_pred['pred'+str(i)]=pred

In [71]:
df_test['prob'] = df_pred.mean(1)

In [72]:
df_test

,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,miss,mrs,master,mr,prob
0,3,34.50000,0,0,7.8292,0,1,0,1,0,0.0,0.0,0.0,1.0,0.132563
1,3,47.00000,1,0,7.0000,1,0,0,0,1,0.0,1.0,0.0,0.0,0.143608
2,2,62.00000,0,0,9.6875,0,1,0,1,0,0.0,0.0,0.0,1.0,0.135920
3,3,27.00000,0,0,8.6625,0,1,0,0,1,0.0,0.0,0.0,1.0,0.264183
4,3,22.00000,1,1,12.2875,1,0,0,0,1,0.0,1.0,0.0,0.0,0.139613
5,3,14.00000,0,0,9.2250,0,1,0,0,1,0.0,0.0,0.0,1.0,0.313678
6,3,30.00000,0,0,7.6292,1,0,0,1,0,1.0,0.0,0.0,0.0,0.059120
7,2,26.00000,1,1,29.0000,0,1,0,0,1,0.0,0.0,0.0,1.0,0.319704
8,3,18.00000,0,0,7.2292,1,0,1,0,0,0.0,1.0,0.0,0.0,0.609895
9,3,21.00000,2,0,24.1500,0,1,0,0,1,0.0,0.0,0.0,1.0,0.206053
10,3,30.27259,0,0,7.8958,0,1,0,0,1,0.0,0.0,0.0,1.0,0.252639
11,1,46.00000,0,0,26.0000,0,1,0,0,1,0.0,0.0,0.0,1.0,0.635664
12,1,23.00000,1,0,82.2667,1,0,0,0,1,0.0,1.0,0.0,0.0,0.690354
13,2,63.00000,1,0,26.0000,0,1,0,0,1,0.0,0.0,0.0,1.0,0.262108
14,1,47.00000,1,0,61.1750,1,0,0,0,1,0.0,1.0,0.0,0.0,0.567484
15,2,24.00000,1,0,27.7208,1,0,1,0,0,0.0,1.0,0.0,0.0,0.839467
16,2,35.00000,0,0,12.3500,0,1,0,1,0,0.0,0.0,0.0,1.0,0.174840
17,3,21.00000,0,0,7.2250,0,1,1,0,0,0.0,0.0,0.0,1.0,0.710971
18,3,27.00000,1,0,7.9250,1,0,0,0,1,1.0,0.0,0.0,0.0,0.088585
19,3,45.00000,0,0,7.2250,1,0,1,0,0,0.0,1.0,0.0,0.0,0.300088
20,1,55.00000,1,0,59.4000,0,1,1,0,0,0.0,0.0,0.0,1.0,0.966565
21,3,9.00000,0,1,3.1708,0,1,0,0,1,0.0,0.0,1.0,0.0,0.251584
22,1,30.27259,0,0,31.6833,1,0,0,0,1,0.0,1.0,0.0,0.0,0.697519
23,1,21.00000,0,1,61.3792,0,1,1,0,0,0.0,0.0,0.0,1.0,0.996917
24,1,48.00000,1,3,262.3750,1,0,1,0,0,0.0,1.0,0.0,0.0,0.869950
25,3,50.00000,1,0,14.5000,0,1,0,0,1,0.0,0.0,0.0,1.0,0.189120
26,1,22.00000,0,1,61.9792,1,0,1,0,0,1.0,0.0,0.0,0.0,0.937339
27,3,22.50000,0,0,7.2250,0,1,1,0,0,0.0,0.0,0.0,1.0,0.688294
28,1,41.00000,0,0,30.5000,0,1,0,0,1,0.0,0.0,0.0,1.0,0.674063
29,3,30.27259,2,0,21.6792,0,1,1,0,0,0.0,0.0,0.0,1.0,0.241787
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388,3,21.00000,0,0,7.7500,0,1,0,1,0,0.0,0.0,0.0,1.0,0.147465
389,3,6.00000,3,1,21.0750,0,1,0,0,1,0.0,0.0,1.0,0.0,0.112941
390,1,23.00000,0,0,93.5000,0,1,0,0,1,0.0,0.0,0.0,1.0,0.788356
391,1,51.00000,0,1,39.4000,1,0,0,0,1,0.0,1.0,0.0,0.0,0.485228
392,3,13.00000,0,2,20.2500,0,1,0,0,1,0.0,0.0,1.0,0.0,0.163752
393,2,47.00000,0,0,10.5000,0,1,0,0,1,0.0,0.0,0.0,1.0,0.297649
394,3,29.00000,3,1,22.0250,0,1,0,0,1,0.0,0.0,0.0,1.0,0.107452
395,1,18.00000,1,0,60.0000,1,0,0,0,1,0.0,1.0,0.0,0.0,0.717219
396,3,24.00000,0,0,7.2500,0,1,0,1,0,0.0,0.0,0.0,1.0,0.142908
397,1,48.00000,1,1,79.2000,1,0,1,0,0,0.0,1.0,0.0,0.0,0.941734
398,3,22.00000,0,0,7.7750,0,1,0,0,1,0.0,0.0,0.0,1.0,0.277630
399,3,31.00000,0,0,7.7333,0,1,0,1,0,0.0,0.0,0.0,1.0,0.136090
400,1,30.00000,0,0,164.8667,1,0,0,0,1,1.0,0.0,0.0,0.0,0.468932
401,2,38.00000,1,0,21.0000,0,1,0,0,1,0.0,0.0,0.0,1.0,0.335601
402,1,22.00000,0,1,59.4000,1,0,1,0,0,1.0,0.0,0.0,0.0,0.938835
403,1,17.00000,0,0,47.1000,0,1,0,0,1,0.0,0.0,0.0,1.0,0.884194
404,1,43.00000,1,0,27.7208,0,1,1,0,0,0.0,0.0,0.0,1.0,0.983681
405,2,20.00000,0,0,13.8625,0,1,1,0,0,0.0,0.0,0.0,1.0,0.977329
406,2,23.00000,1,0,10.5000,0,1,0,0,1,0.0,0.0,0.0,1.0,0.360738
407,1,50.00000,1,1,211.5000,0,1,1,0,0,0.0,0.0,0.0,1.0,0.944180
408,3,30.27259,0,0,7.7208,1,0,0,1,0,1.0,0.0,0.0,0.0,0.059069
409,3,3.00000,1,1,13.7750,1,0,0,0,1,1.0,0.0,0.0,0.0,0.090745
410,3,30.27259,0,0,7.7500,1,0,0,1,0,1.0,0.0,0.0,0.0,0.059095
411,1,37.00000,1,0,90.0000,1,0,0,1,0,0.0,1.0,0.0,0.0,0.338753
412,3,28.00000,0,0,7.7750,1,0,0,0,1,1.0,0.0,0.0,0.0,0.117501
413,3,30.27259,0,0,8.0500,0,1,0,0,1,0.0,0.0,0.0,1.0,0.253135
414,1,39.00000,0,0,108.9000,1,0,1,0,0,0.0,0.0,0.0,0.0,0.985864
415,3,38.50000,0,0,7.2500,0,1,0,0,1,0.0,0.0,0.0,1.0,0.236659
416,3,30.27259,0,0,8.0500,0,1,0,0,1,0.0,0.0,0.0,1.0,0.253135
417,3,30.27259,1,1,22.3583,0,1,1,0,0,0.0,0.0,1.0,0.0,0.413761

In [ ]:
X = df_test.as_matrix().astype(np.float32)